### ISSUE TITLE
TypeError: hex_.replace is not a function. (In 'hex_.replace("0x", "")', 'hex_.replace' is undefined)

### ISSUE THREAD

**Issue by abheektripathy** [bcnmy/biconomy-client-sdk#423]
im trying to send an txn to using `.sendTransaction()` for a crosschain swap using LIFI(got txn data like [this](https://arc.net/l/quote/dfkgbwrl)), im getting a typerror.
``` typescript
const tx = {
data: "0x83f319170000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000022000000000000000000000000000000000000000000000000000000000000008c089ce941ffab1ae94b6fcb4446f11411dbd230d918ccc4b3949dd1b275287b172000000000000000000000000000000000000000000000000000000000000014000000000000000000000000000000000000000000000000000000000000001800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c2132d05d31c914a87c6611c10748aeb04b58e8f00000000000000000000000020b59ee457f3013cc2e556993f961803aabd682100000000000000000000000000000000000000000000000000000000000f34d70000000000000000000000000000000000000000000000000000000000000064000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000006616d61726f6b000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000086c6966692d6170690000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000002000000000000000000000000039e3e49c99834c9573c9fc7ff5a4b226cd7b0e630000000000000000000000006d310348d5c12009854dfcf72e0df9027e8cb4f40000000000000000000000002791bca1f2de4661ed88a30c99a7a9449aa84174000000000000000000000000c2132d05d31c914a87c6611c10748aeb04b58e8f00000000000000000000000000000000000000000000000000000000000f424000000000000000000000000000000000000000000000000000000000000000e000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000544301a37200000000000000000000000002791bca1f2de4661ed88a30c99a7a9449aa84174000000000000000000000000c2132d05d31c914a87c6611c10748aeb04b58e8f00000000000000000000000000000000000000000000000000000000000f424000000000000000000000000000000000000000000000000000000000000f34d7000000000000000000000000000000000000000000000000000000000000016000000000000000000000000000000000000000000000000000000000000001e000000000000000000000000000000000000000000000000000000000000002600000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000030000000000000000000000000000000000000000000000000000000000000004e00000000000000000000000000000000000000000000000000000000065d3696600000000000000000000000000000000000000000000000000000000000000030000000000000000000000006c30be15d88462b788dea7c6a860a2ccaf7b2670000000000000000000000000e373df144a70bccc10190f97bede647d1ed6cfc80000000000000000000000003037e79fce8817a6f21196d8d93c80f53abb926700000000000000000000000000000000000000000000000000000000000000030000000000000000000000001093ced81987bf532c2b7907b2a8525cd0c172950000000000000000000000008929d3fea77398f64448c85015633c2d6472fb29000000000000000000000000445fe580ef8d70ff569ab36e80c647af338db35100000000000000000000000000000000000000000000000000000000000000040000000000000000000000001093ced81987bf532c2b7907b2a8525cd0c172950000000000000000000000008929d3fea77398f64448c85015633c2d6472fb290000000000000000000000003037e79fce8817a6f21196d8d93c80f53abb926700000000000000000000000039e3e49c99834c9573c9fc7ff5a4b226cd7b0e630000000000000000000000000000000000000000000000000000000000000003000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000a00000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000001e000000000000000000000000000000000000000000000000000000000000271000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008f3cf7ad23cd3cadbd9735aff958023239c6a063000000000000000000000000c2132d05d31c914a87c6611c10748aeb04b58e8f000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000e000000000000000000000000020b59ee457f3013cc2e556993f961803aabd68210000000000000000000000000000000000000000000000000007a7a9f9f91645000000000000000000000000000000000000000000000000000000000000003200000000000000000000000020b59ee457f3013cc2e556993f961803aabd68210000000000000000000000000000000000000000000000000000000000676e6f00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  to: "0x1231DEB6f5749EF6cE6943a275A1D3E7486F4EaE",
};

const OP = await smartWallet.sendTransaction(tx, {
  paymasterServiceData: {
    mode: PaymasterMode.SPONSORED,
  },
});

const { transactionHash } = await OP.waitForTxHash();
console.log("transactionHash", transactionHash);

```

i have checked the api key + bundler url configs, any idea of what might be going wrong here?

here's the full error
```
 5 |     return padBytes(hexOrBytes, { dir, size });
 6 | }
 7 | export function padHex(hex_, { dir, size = 32 } = {}) {
 8 |     if (size === null)
 9 |         return hex_;
10 |     const hex = hex_.replace('0x', '');
                     ^
TypeError: hex_.replace is not a function. (In 'hex_.replace("0x", "")', 'hex_.replace' is undefined)
      at padHex (/Users/abheektripathy/Documents/code/avail/nexus-cli/node_modules/viem/_esm/utils/data/pad.js:10:17)
      at encodeBytes (/Users/abheektripathy/Documents/code/avail/nexus-cli/node_modules/viem/_esm/utils/abi/encodeAbiParameters.js:142:22)
      at prepareParams (/Users/abheektripathy/Documents/code/avail/nexus-cli/node_modules/viem/_esm/utils/abi/encodeAbiParameters.js:31:29)
      at encodeAbiParameters (/Users/abheektripathy/Documents/code/avail/nexus-cli/node_modules/viem/_esm/utils/abi/encodeAbiParameters.js:19:28)
      at encodeFunctionData (/Users/abheektripathy/Documents/code/avail/nexus-cli/node_modules/viem/_esm/utils/abi/encodeFunctionData.js:26:11)
      at encodeExecute (/Users/abheektripathy/Documents/code/avail/nexus-cli/node_modules/@biconomy/account/dist/esm/BiconomySmartAccountV2.js:1:7192)
      at /Users/abheektripathy/Documents/code/avail/nexus-cli/node_modules/@biconomy/account/dist/esm/BiconomySmartAccountV2.js:1:12812
      at processTicksAndRejections (:61:77)
      
 ```

**Comment by joepegler** [comment]
We have countless tests that run this same code that are passing, so it's difficult to help here without wider context. Would be great to have a minimal reducible project with the issue in a codesandbox or similar. Short that there is some more information you could provide that might help:

- The code where you create the smartWalletClient
- The environment you're working on (Is it a frontend?)
- The package.lock with the package versions you're using

**Comment by abheektripathy** [comment]
during sendTransaction, let me check with vanilla node once.

**Comment by abheektripathy** [comment]
@joepegler ran it in a new next.js project, still same error.

**Comment by joepegler** [comment]
Hmm, found a relevant looking Minimal Reproducible Example raised with viem: https://stackblitz.com/edit/viem-getting-started-dmhpsz?file=main.ts.

**Comment by joepegler** [comment]
https://github.com/wevm/viem/discussions/927
