### ISSUE TITLE
[BUG] Error [ERR_REQUIRE_ESM]: require() of ES Module

### ISSUE THREAD

**Issue by jeftarmascarenhas** [bcnmy/biconomy-client-sdk#575]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

4.6.1

### Current Behavior

I updated @biconomy/account module to latest, when I run my node api its does not work.
My api using Nodejs, typescript and express.js

```bash
> ts-node-dev --transpile-only src/app.ts --watch 'src/' -e ts,js,json | pino-pretty -c
[INFO] 17:56:45 ts-node-dev ver. 2.0.0 (using ts-node ver. 10.9.2, typescript ver. 5.3.2)
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/user/projects/blockchain/myproject/node_modules/@silencelaboratories/walletprovider-sdk/dist/index.js from /home/user/projects/blockchain/myproject/node_modules/@biconomy/account/dist/_cjs/modules/sessions/dan.js not supported.
Instead change the require of index.js in /home/user/projects/blockchain/myproject/node_modules/@biconomy/account/dist/_cjs/modules/sessions/dan.js to a dynamic import() which is available in all CommonJS modules.
    at require.extensions..jsx.require.extensions..js (/tmp/ts-node-dev-hook-5900037615891709.js:114:20)
    at Object.nodeDevHook [as .js] (/home/user/projects/blockchain/myproject/node_modules/ts-node-dev/lib/hook.js:63:13)
    at Object.<anonymous> (/home/user/projects/blockchain/myproject/node_modules/@biconomy/account/dist/_cjs/modules/sessions/dan.js:4:30)
    at Module._compile (/home/user/projects/blockchain/myproject/node_modules/source-map-support/source-map-support.js:568:25)
    at require.extensions..jsx.require.extensions..js (/tmp/ts-node-dev-hook-5900037615891709.js:114:20)
    at Object.nodeDevHook [as .js] (/home/user/projects/blockchain/myproject/node_modules/ts-node-dev/lib/hook.js:63:13)
    at Object.<anonymous> (/home/user/projects/blockchain/myproject/node_modules/@biconomy/account/dist/_cjs/modules/index.js:19:22)
    at Module._compile (/home/user/projects/blockchain/myproject/node_modules/source-map-support/source-map-support.js:568:25)
    at require.extensions..jsx.require.extensions..js (/tmp/ts-node-dev-hook-5900037615891709.js:114:20)
    at Object.nodeDevHook [as .js] (/home/user/projects/blockchain/myproject/node_modules/ts-node-dev/lib/hook.js:63:13)
    at Object.<anonymous> (/home/user/projects/blockchain/myproject/node_modules/@biconomy/account/dist/_cjs/account/BiconomySmartAccountV2.js:7:19)
    at Module._compile (/home/user/projects/blockchain/myproject/node_modules/source-map-support/source-map-support.js:568:25)
    at require.extensions..jsx.require.extensions..js (/tmp/ts-node-dev-hook-5900037615891709.js:114:20)
    at Object.nodeDevHook [as .js] (/home/user/projects/blockchain/myproject/node_modules/ts-node-dev/lib/hook.js:63:13)
    at Object.<anonymous> (/home/user/projects/blockchain/myproject/node_modules/@biconomy/account/dist/_cjs/account/index.js:5:37)
    at Module._compile (/home/user/projects/blockchain/myproject/node_modules/source-map-support/source-map-support.js:568:25)
    at require.extensions..jsx.require.extensions..js (/tmp/ts-node-dev-hook-5900037615891709.js:114:20)
    at Object.nodeDevHook [as .js] (/home/user/projects/blockchain/myproject/node_modules/ts-node-dev/lib/hook.js:63:13)
    at Object.<anonymous> (/home/user/projects/blockchain/myproject/node_modules/@biconomy/account/dist/_cjs/index.js:4:22)
    at Module._compile (/home/user/projects/blockchain/myproject/node_modules/source-map-support/source-map-support.js:568:25)
    at require.extensions..jsx.require.extensions..js (/tmp/ts-node-dev-hook-5900037615891709.js:114:20)
    at Object.nodeDevHook [as .js] (/home/user/projects/blockchain/myproject/node_modules/ts-node-dev/lib/hook.js:63:13)
    at Object.<anonymous> (/home/user/projects/blockchain/myproject/src/MzicSmartWallet/infra/accountBiconomyAdapter.ts:5:19)
    at Module._compile (/home/user/projects/blockchain/myproject/node_modules/source-map-support/source-map-support.js:568:25)
    at m._compile (/tmp/ts-node-dev-hook-5900037615891709.js:69:33)
    at require.extensions..jsx.require.extensions..js (/tmp/ts-node-dev-hook-5900037615891709.js:114:20)
    at require.extensions.<computed> (/tmp/ts-node-dev-hook-5900037615891709.js:71:20)
    at Object.nodeDevHook [as .ts] (/home/user/projects/blockchain/myproject/node_modules/ts-node-dev/lib/hook.js:63:13)
    at Object.<anonymous> (/home/user/projects/blockchain/myproject/src/MzicSmartWallet/mzicSmartAccount.ts:10:34)
    at Module._compile (/home/user/projects/blockchain/myproject/node_modules/source-map-support/source-map-support.js:568:25)
    at m._compile (/tmp/ts-node-dev-hook-5900037615891709.js:69:33)
    at require.extensions..jsx.require.extensions..js (/tmp/ts-node-dev-hook-5900037615891709.js:114:20)
    at require.extensions.<computed> (/tmp/ts-node-dev-hook-5900037615891709.js:71:20)
    at Object.nodeDevHook [as .ts] (/home/user/projects/blockchain/myproject/node_modules/ts-node-dev/lib/hook.js:63:13)
    at Object.<anonymous> (/home/user/projects/blockchain/myproject/src/MzicSmartWallet/index.ts:17:14)
    at Module._compile (/home/user/projects/blockchain/myproject/node_modules/source-map-support/source-map-support.js:568:25)
    at m._compile (/tmp/ts-node-dev-hook-5900037615891709.js:69:33)
    at require.extensions..jsx.require.extensions..js (/tmp/ts-node-dev-hook-5900037615891709.js:114:20)
    at require.extensions.<computed> (/tmp/ts-node-dev-hook-5900037615891709.js:71:20)
    at Object.nodeDevHook [as .ts] (/home/user/projects/blockchain/myproject/node_modules/ts-node-dev/lib/hook.js:63:13)
    at Object.<anonymous> (/home/user/projects/blockchain/myproject/src/service/gasService.ts:38:27)
    at Module._compile (/home/user/projects/blockchain/myproject/node_modules/source-map-support/source-map-support.js:568:25)
    at m._compile (/tmp/ts-node-dev-hook-5900037615891709.js:69:33)
    at require.extensions..jsx.require.extensions..js (/tmp/ts-node-dev-hook-5900037615891709.js:114:20)
    at require.extensions.<computed> (/tmp/ts-node-dev-hook-5900037615891709.js:71:20)
    at Object.nodeDevHook [as .ts] (/home/user/projects/blockchain/myproject/node_modules/ts-node-dev/lib/hook.js:63:13)
    at Object.<anonymous> (/home/user/projects/blockchain/myproject/src/service/royaltyService.ts:32:38)
    at Module._compile (/home/user/projects/blockchain/myproject/node_modules/source-map-support/source-map-support.js:568:25)
    at m._compile (/tmp/ts-node-dev-hook-5900037615891709.js:69:33)
    at require.extensions..jsx.require.extensions..js (/tmp/ts-node-dev-hook-5900037615891709.js:114:20)
    at require.extensions.<computed> (/tmp/ts-node-dev-hook-5900037615891709.js:71:20)
    at Object.nodeDevHook [as .ts] (/home/user/projects/blockchain/myproject/node_modules/ts-node-dev/lib/hook.js:63:13)
    at Object.<anonymous> (/home/user/projects/blockchain/myproject/src/service/walletService.ts:6:42)
    at Module._compile (/home/user/projects/blockchain/myproject/node_modules/source-map-support/source-map-support.js:568:25)
    at m._compile (/tmp/ts-node-dev-hook-5900037615891709.js:69:33)
    at require.extensions..jsx.require.extensions..js (/tmp/ts-node-dev-hook-5900037615891709.js:114:20)
    at require.extensions.<computed> (/tmp/ts-node-dev-hook-5900037615891709.js:71:20)
    at Object.nodeDevHook [as .ts] (/home/user/projects/blockchain/myproject/node_modules/ts-node-dev/lib/hook.js:63:13)
    at Object.<anonymous> (/home/user/projects/blockchain/myproject/src/service/shareService.ts:9:41)
    at Module._compile (/home/user/projects/blockchain/myproject/node_modules/source-map-support/source-map-support.js:568:25)
    at m._compile (/tmp/ts-node-dev-hook-5900037615891709.js:69:33)
    at require.extensions..jsx.require.extensions..js (/tmp/ts-node-dev-hook-5900037615891709.js:114:20)
    at require.extensions.<computed> (/tmp/ts-node-dev-hook-5900037615891709.js:71:20)
    at Object.nodeDevHook [as .ts] (/home/user/projects/blockchain/myproject/node_modules/ts-node-dev/lib/hook.js:63:13)
    at Object.<anonymous> (/home/user/projects/blockchain/myproject/src/service/nftService.ts:33:40)
    at Module._compile (/home/user/projects/blockchain/myproject/node_modules/source-map-support/source-map-support.js:568:25)
    at m._compile (/tmp/ts-node-dev-hook-5900037615891709.js:69:33)
    at require.extensions..jsx.require.extensions..js (/tmp/ts-node-dev-hook-5900037615891709.js:114:20)
    at require.extensions.<computed> (/tmp/ts-node-dev-hook-5900037615891709.js:71:20)
    at Object.nodeDevHook [as .ts] (/home/user/projects/blockchain/myproject/node_modules/ts-node-dev/lib/hook.js:63:13)
    at Object.<anonymous> (/home/user/projects/blockchain/myproject/src/controller/nftController.ts:7:38)
    at Module._compile (/home/user/projects/blockchain/myproject/node_modules/source-map-support/source-map-support.js:568:25)
    at m._compile (/tmp/ts-node-dev-hook-5900037615891709.js:69:33)
    at require.extensions..jsx.require.extensions..js (/tmp/ts-node-dev-hook-5900037615891709.js:114:20)
    at require.extensions.<computed> (/tmp/ts-node-dev-hook-5900037615891709.js:71:20)
    at Object.nodeDevHook [as .ts] (/home/user/projects/blockchain/myproject/node_modules/ts-node-dev/lib/hook.js:63:13)
    at Object.<anonymous> (/home/user/projects/blockchain/myproject/src/server.ts:14:41)
    at Module._compile (/home/user/projects/blockchain/myproject/node_modules/source-map-support/source-map-support.js:568:25)
    at m._compile (/tmp/ts-node-dev-hook-5900037615891709.js:69:33)
    at require.extensions..jsx.require.extensions..js (/tmp/ts-node-dev-hook-5900037615891709.js:114:20)
    at require.extensions.<computed> (/tmp/ts-node-dev-hook-5900037615891709.js:71:20)
    at Object.nodeDevHook [as .ts] (/home/user/projects/blockchain/myproject/node_modules/ts-node-dev/lib/hook.js:63:13)
    at Object.<anonymous> (/home/user/projects/blockchain/myproject/node_modules/ts-node-dev/lib/wrap.js:104:1)
    at Module._compile (/home/user/projects/blockchain/myproject/node_modules/source-map-support/source-map-support.js:568:25)
    at require.extensions..jsx.require.extensions..js (/tmp/ts-node-dev-hook-5900037615891709.js:95:24)
[ERROR] 17:56:46 Error: require() of ES Module /home/user/projects/blockchain/myproject/node_modules/@silencelaboratories/walletprovider-sdk/dist/index.js from /home/user/projects/blockchain/myproject/node_modules/@biconomy/account/dist/_cjs/modules/sessions/dan.js not supported.
Instead change the require of index.js in /home/user/projects/blockchain/myproject/node_modules/@biconomy/account/dist/_cjs/modules/sessions/dan.js to a dynamic import() which is available in all CommonJS modules.

```

### Package.json (or lockfile) content

```bash
{
  "name": "ms-blockchain",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "node ./dist/src/app.js",
    "build": "rimraf ./dist && tsc -p .",
    "lint": "eslint ./src --ext .ts",
    "lint:fix": "eslint ./src --ext .ts --fix",
    "format": "prettier --write src/**/*.ts",
    "dev": "ts-node-dev --transpile-only src/app.ts --watch 'src/' -e ts,js,json | pino-pretty -c",
    "prepare": "husky install"
  },
  "author": "",
  "license": "ISC",
  "engines": {
    "node": ">=18"
  },
  "dependencies": {
    "@aws-sdk/client-s3": "^3.428.0",
    "@biconomy/account": "^4.6.1",
    "@biconomy/bundler": "^4.1.1",
    "@biconomy/common": "^4.1.1",
    "@biconomy/modules": "^4.1.1",
    "@biconomy/paymaster": "^4.1.1",
    "@fireblocks/fireblocks-web3-provider": "^1.2.3",
    "axios": "^1.5.0",
    "config": "^3.3.9",
    "dotenv": "^16.3.1",
    "ethers": "^5.0.5",
    "events": "^3.3.0",
    "express": "^4.18.2",
    "express-openapi-validator": "^5.1.2",
    "express-pino-logger": "^7.0.0",
    "fireblocks-sdk": "^5.6.1",
    "helmet": "^7.1.0",
    "lodash": "^4.17.21",
    "postgres": "^3.4.0",
    "rimraf": "^5.0.5",
    "swagger-jsdoc": "^6.2.8",
    "swagger-ui-dist": "^5.10.5",
    "swagger-ui-express": "^5.0.0",
    "web3": "^4.2.0",
    "web3-utils": "^4.0.7"
  },
  "devDependencies": {
    "@types/config": "^3.3.3",
    "@types/dotenv": "^8.2.0",
    "@types/express": "^4.17.21",
    "@types/express-pino-logger": "^4.0.5",
    "@types/lodash": "^4.17.0",
    "@types/morgan": "^1.9.9",
    "@types/swagger-jsdoc": "^6.0.4",
    "@types/swagger-ui-express": "^4.1.6",
    "@typescript-eslint/eslint-plugin": "^6.13.2",
    "@typescript-eslint/parser": "^6.13.2",
    "ajv": "^8.12.0",
    "eslint": "^8.55.0",
    "eslint-config-prettier": "^9.1.0",
    "husky": "^8.0.0",
    "lint-staged": "^15.2.0",
    "pino-pretty": "^10.3.0",
    "prettier": "^3.1.1",
    "shell-quote": "^1.8.1",
    "ts-node-dev": "^2.0.0",
    "typescript": "^5.3.2"
  }
}

```

**Comment by VGabriel45** [comment]
Hi @jeftarmascarenhas, this is a know issue due to a dependency package we are using in the latest version, we're working on a fix, until then please use the version prior to the latest one. 4.6.0

**Comment by VGabriel45** [comment]
@jeftarmascarenhas you can switch to latest version 4.6.2, issue should be fixed

**Comment by jeftarmascarenhas** [comment]
> @jeftarmascarenhas you can switch to latest version 4.6.2, issue should be fixed

@VGabriel45 I updated to 4.6.2 the issue was fixed. Thank you for your support.
